version: '2'
services:
  platform-admin:
    image: platform/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  platform-api:
    image: platform/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev